#!/usr/bin/env php          // it is a shebang line to indicate the script should be run with PHP interpreter
<?php

use Illuminate\Foundation\Application;  // it is the core of the application
use Symfony\Component\Console\Input\ArgvInput;  // it is a Symphony class used to handle command line arguments (es. php artisan migrate, migrate is an argument)

define('LARAVEL_START', microtime(true));  // it defines a constant to track the start time of the application

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';   // it loads the Composer autoloader

// Bootstrap Laravel and handle the command...
/** @var Application $app */  // it is a PHPDoc comment that indicates the type of $app variable
$app = require_once __DIR__.'/bootstrap/app.php';   // it includes the bootstrap file to create the Laravel instance

$status = $app->handleCommand(new ArgvInput);  // it tells to Laravel to run the command with the argument received as input 

exit($status); // it exits the script with the status code returned by the command  
